-- Project timelines and financing scores — generated by the three macro-agents
-- Stored so they persist across sessions and can be surfaced in the dashboard

create table if not exists public.project_timelines (
  id                        uuid primary key default gen_random_uuid(),
  business_unit_id          uuid not null references public.business_units(id) on delete cascade,
  trade_type                text,
  scope_summary             text,
  total_budget_usd          numeric(14,2),
  phases                    jsonb not null default '[]'::jsonb,
  cashflow_projections      jsonb not null default '[]'::jsonb,
  total_weeks               integer,
  estimated_completion_date date,
  risk_items                jsonb not null default '[]'::jsonb,
  created_by                uuid references auth.users(id),
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);

create index if not exists project_timelines_bu_idx
  on public.project_timelines(business_unit_id, created_at desc);

comment on table public.project_timelines is
  'Renovation Workflow AI output: Gantt phases + weekly cash-flow projections';

-- Financing readiness scores generated by Lending Capital AI
create table if not exists public.financing_scores (
  id                uuid primary key default gen_random_uuid(),
  business_unit_id  uuid not null references public.business_units(id) on delete cascade,
  readiness_score   numeric(5,2) not null,
  readiness_band    text not null check (readiness_band in ('ready','near_ready','needs_work','not_ready')),
  gaps              jsonb not null default '[]'::jsonb,
  lender_shortlist  jsonb not null default '[]'::jsonb,
  indicative_terms  jsonb,
  created_by        uuid references auth.users(id),
  created_at        timestamptz not null default now()
);

create index if not exists financing_scores_bu_idx
  on public.financing_scores(business_unit_id, created_at desc);

comment on table public.financing_scores is
  'Lending Capital AI output: readiness score + lender shortlist + indicative terms';

-- RLS
alter table public.project_timelines enable row level security;
alter table public.financing_scores enable row level security;

create policy "bu members read project_timelines"
  on public.project_timelines for select
  using (business_unit_id in (
    select business_unit_id from public.business_unit_members where user_id = auth.uid()
  ));

create policy "service role full access project_timelines"
  on public.project_timelines for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create policy "bu members read financing_scores"
  on public.financing_scores for select
  using (business_unit_id in (
    select business_unit_id from public.business_unit_members where user_id = auth.uid()
  ));

create policy "service role full access financing_scores"
  on public.financing_scores for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
