// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("Supabase environment variables are missing. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    // Send a heartbeat every 25s to keep the WebSocket alive through proxies
    // and NAT gateways that drop idle connections after ~30-60s.
    heartbeatIntervalMs: 25_000,
    // Reconnect after 1s, 2s, 4s … capped at 10s.
    reconnectAfterMs: (tries: number) => Math.min(1_000 * 2 ** tries, 10_000),
    // Supabase realtime timeout before declaring a channel dead.
    timeout: 30_000,
  },
});

export const invokeEdgeFunction = <T>(functionName: string, body?: unknown) =>
  supabase.functions.invoke<T>(functionName, {
    body,
  });
